# Generated by Django 4.1.7 on 2023-04-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0002_queries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queries',
            name='query',
        ),
        migrations.AddField(
            model_name='queries',
            name='processed_query',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='queries',
            name='raw_query',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
