# Generated by Django 4.1.8 on 2023-04-18 23:49

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0002_category_answerresource_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_query', models.TextField()),
                ('processed_query', models.TextField()),
                ('encoded_query', picklefield.fields.PickledObjectField(editable=False)),
                ('occurrences', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk_app.category')),
            ],
        ),
    ]
