# Generated by Django 4.1.7 on 2023-03-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0002_answerresource_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerresource',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='answerresource',
            name='title',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='answerresource',
            name='url',
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
