# Generated by Django 4.1.8 on 2023-04-19 00:15

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0003_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='encoded_query',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
