# Generated by Django 4.1.7 on 2023-03-22 16:15

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('helpdesk_app', '0003_answerresource_updated_keyword_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerresource',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
