# Generated by Django 4.1.8 on 2023-04-19 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0003_answerresource_clicks_answerresource_searches_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerresource',
            old_name='searches',
            new_name='appearances',
        ),
    ]
