# Generated by Django 4.1.8 on 2023-04-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0004_rename_searches_answerresource_appearances'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerresource',
            old_name='thumbsUps',
            new_name='thumbsDowns',
        ),
    ]
