# Generated by Django 4.1.7 on 2023-03-22 17:08

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('helpdesk_app', '0006_delete_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerresource',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Related keywords for this resource', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
