# Generated by Django 4.1.7 on 2023-03-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0007_alter_answerresource_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerresource',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
